image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - name: Python setup
    init: |
      pip3 install -r scripts/requirements.txt

  - name: Mathlib setup
    init: lake exe cache get

  - name: build HTML and open preview
    command: |
      python3 scripts/mkall.py
      make html
      python3 -m http.server 8000 --directory build/html
