image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - name: Python setup and build HTML
    init: |
      pip3 install -r scripts/requirements.txt
      python3 scripts/mkall.py
      make html
    command: python3 -m http.server 8000 --directory build/html

  - name: mathlib setup
    init: lake exe cache get
